development:
  secret_key_base: a9791f3589ef135816dfe5e563341a5293fa0c4d896ee3ebad70b04950c09aeea74d652e9d2695b4e6d9959a0d07cc6ad2628b468ac26ed717372c9c383718d8

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  action_mailer:
    username: <%= ENV['SMTP_USERNAME'] %>
    password: <%= ENV['SMTP_PASSWORD'] %>
    domain: <%= ENV['HOST_URL'] %>
    address: smtp.sendgrid.net
    port: 587
    authentication: :plain
    enable_starttls_auto: true
